version: '3'

services:
  vuln-app:
    image: michelangelodorado/vuln-app:latest
    ports:
      - "3000:3000"
      - "80:80"
    networks:
      - mynetwork

  currency-api:
    image: michelangelodorado/currency-api:latest
    ports:
      - "8080:8080"
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
